### ISSUE TITLE
Incomplete forms?

### ISSUE THREAD

**Issue by dush-t** [siddhantkhandelwal/Checkmate2019#8]
sign_up_team page only shows team name and password fields. Should also show a username field otherwise there could be clashes (because team names are not unique).

**Comment by ashryaagr** [comment]
We can use team name as username

**Comment by siddhantkhandelwal** [comment]
Have you tested this? @dush-t @ashryaagr

**Comment by siddhantkhandelwal** [comment]
Have you tested this? @dush-t @ashryaagr
